name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mik3y/gatsby-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master
          deploy-repo: kegbot.github.io
